name: CI

on:
  workflow_dispatch:

env:
  DOCKER_IMAGE: spring-boot-web-two
  DOCKER_USERNAME: luissanzaguilar
  DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: Docker Login
        uses: docker/login-action@v3.4.0
        with:
          username: ${{env.DOCKER_USERNAME}}
          password: ${{env.DOCKER_PASSWORD}}
      - name: Build Docker Image
        run: docker build -t ${{env.DOCKER_IMAGE}}:${{github.sha}} .
      - name: Tag Docker Image
        run: docker tag $DOCKER_IMAGE:${{github.sha}} $DOCKER_USERNAME/$DOCKER_IMAGE:latest
      - name: Push docker image
        # docker push $DOCKER_IMAGE:${{github.sha}}          
        run: |
          docker push $DOCKER_USERNAME/$DOCKER_IMAGE:latest
  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Docker Login
        uses: docker/login-action@v3.4.0
        with:
          username: ${{env.DOCKER_USERNAME}}
          password: ${{env.DOCKER_PASSWORD}}
      - name: Pull docker image
        # docker pull $DOCKER_IMAGE:${{github.sha}}          
        run: |
          docker pull $DOCKER_USERNAME/$DOCKER_IMAGE:latest
      - name: Docker run
        run: |
          docker run -d -p 8080:8080 $DOCKER_USERNAME/$DOCKER_IMAGE:latest
          
          

          

        
          

